controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute



error_404:
    path: /{catchall}
    controller: App\Controller\ErrorController::pageNotFound
    requirements:
        catchall: '.*'

